# Generated by Django 3.2.5 on 2021-08-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Время действия')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('type', models.TextField(verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'история действий',
                'verbose_name_plural': 'история действий',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(verbose_name='Время создания')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('currency', models.TextField(verbose_name='Валюта')),
                ('btc_value', models.IntegerField(verbose_name='BTC')),
                ('rub_value', models.IntegerField(verbose_name='RUB')),
                ('code', models.TextField(verbose_name='Код')),
                ('status', models.IntegerField(verbose_name='Статус')),
                ('used_by_id', models.IntegerField(verbose_name='ID активировшего')),
                ('btc_balance', models.IntegerField(verbose_name='Баланс BTC')),
                ('rub_balance', models.IntegerField(verbose_name='Баланс RUB')),
                ('end_dt', models.DateTimeField(verbose_name='Время активации')),
            ],
            options={
                'verbose_name': 'код',
                'verbose_name_plural': 'коды',
                'db_table': 'codes',
            },
        ),
        migrations.CreateModel(
            name='exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('create_dt', models.DateTimeField(verbose_name='Время создания')),
                ('type', models.IntegerField(verbose_name='Тип')),
                ('btc_value', models.IntegerField(verbose_name='BTC')),
                ('rub_value', models.IntegerField(verbose_name='RUB')),
                ('status', models.IntegerField(verbose_name='Статус')),
                ('commission', models.IntegerField(verbose_name='Комиссия')),
                ('currency_btc', models.IntegerField(verbose_name='Курс BTC')),
                ('currency_usd', models.IntegerField(verbose_name='Курс USD')),
                ('end_dt', models.DateTimeField(verbose_name='Время окончания')),
                ('admin_id', models.IntegerField(verbose_name='ID администратора')),
                ('curs_formula', models.CharField(max_length=64, verbose_name='currency_usd')),
            ],
            options={
                'verbose_name': 'обмен',
                'verbose_name_plural': 'обмен',
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='replenish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('create_dt', models.DateTimeField(verbose_name='Время создания')),
                ('currency', models.IntegerField(verbose_name='Валюта')),
                ('btc_value', models.IntegerField(verbose_name='BTC')),
                ('rub_value', models.IntegerField(verbose_name='RUB')),
                ('status', models.IntegerField(verbose_name='Статус')),
                ('country', models.IntegerField(verbose_name='Страна')),
                ('city', models.IntegerField(verbose_name='Город')),
                ('commission', models.IntegerField(verbose_name='Комиссия')),
                ('wallet_to', models.IntegerField(verbose_name='На кошелек')),
                ('btc_balance', models.IntegerField(verbose_name='Баланс BTC')),
                ('rub_balance', models.IntegerField(verbose_name='Баланс RUB')),
                ('answer', models.IntegerField(verbose_name='Причина отказа')),
                ('wallet_from', models.IntegerField(verbose_name='С кошелька')),
                ('txid', models.IntegerField(verbose_name='txid')),
                ('end_dt', models.DateTimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'пополнение',
                'verbose_name_plural': 'пополнение',
                'db_table': 'replenish',
            },
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время сообщения')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('admin_id', models.IntegerField(verbose_name='ID администратора')),
                ('message', models.TextField(verbose_name='Текст')),
                ('from_who', models.TextField(verbose_name='Кто написал')),
                ('connect_id', models.IntegerField(verbose_name='connect_id')),
            ],
            options={
                'verbose_name': 'support',
                'verbose_name_plural': 'support',
                'db_table': 'support',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('username', models.TextField(verbose_name='Username')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('email', models.TextField(verbose_name='email')),
                ('fio', models.TextField(verbose_name='ФИО')),
                ('btc_value', models.IntegerField(verbose_name='Баланс BTC')),
                ('rub_value', models.IntegerField(verbose_name='Баланс RUB')),
                ('invited_by', models.IntegerField(verbose_name='Кем приглашен')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('status', models.IntegerField(verbose_name='Статус')),
                ('bonuses', models.IntegerField(verbose_name='Бонусы')),
                ('history_email', models.TextField(verbose_name='История email')),
                ('history_telephone', models.TextField(verbose_name='История телефона')),
                ('block', models.TextField(verbose_name='Блокировка')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.TextField(verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'кошелек',
                'verbose_name_plural': 'кошельки',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('create_dt', models.DateTimeField(verbose_name='Время создания')),
                ('currency', models.IntegerField(verbose_name='Валюта')),
                ('btc_value', models.IntegerField(verbose_name='BTC')),
                ('rub_value', models.IntegerField(verbose_name='RUB')),
                ('btc_payment', models.IntegerField(verbose_name='Кошелек BTC')),
                ('rub_payment', models.IntegerField(verbose_name='Реквизиты RUB')),
                ('status', models.IntegerField(verbose_name='Статус')),
                ('commission', models.IntegerField(verbose_name='Комиссия')),
                ('btc_balance', models.IntegerField(verbose_name='Баланс BTC')),
                ('rub_balance', models.IntegerField(verbose_name='Баланс RUB')),
                ('answer', models.IntegerField(verbose_name='Причина отказа')),
                ('txid', models.IntegerField(verbose_name='txid')),
                ('end_dt', models.DateTimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'вывод',
                'verbose_name_plural': 'вывод',
                'db_table': 'withdraw',
            },
        ),
    ]
