# Generated by Django 3.2.5 on 2021-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(null=True, verbose_name='ID админа')),
                ('login_dt', models.DateTimeField(null=True, verbose_name='Дата входа')),
                ('permissions', models.TextField(blank=True, null=True, verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'админ',
                'verbose_name_plural': 'админы',
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replenish', models.PositiveIntegerField(verbose_name='Комиссия ввода в %')),
                ('exchange', models.PositiveIntegerField(verbose_name='Комиссия обмена в %')),
                ('withdraw', models.PositiveIntegerField(verbose_name='Комиссия вывода RUB в %')),
                ('withdraw_btc', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Комиссия вывода BTC в btc')),
            ],
            options={
                'verbose_name': 'комиссия',
                'verbose_name_plural': 'комиссия',
                'db_table': 'commission',
            },
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(null=True, verbose_name='ID пользователя')),
                ('dt', models.DateTimeField(null=True, verbose_name='Время транзакции')),
                ('got', models.TextField(null=True, verbose_name='Получил')),
                ('sent', models.TextField(null=True, verbose_name='Отправил')),
                ('balance_was', models.TextField(null=True, verbose_name='Баланс был')),
                ('balance', models.TextField(null=True, verbose_name='Баланс стал')),
                ('type', models.TextField(null=True, verbose_name='Тип')),
                ('commission', models.TextField(null=True, verbose_name='Коммиссия')),
                ('info', models.TextField(null=True, verbose_name='Информация')),
                ('status', models.TextField(null=True, verbose_name='Статус')),
                ('end_dt', models.DateTimeField(null=True, verbose_name='Время окончания')),
                ('answer', models.TextField(null=True, verbose_name='Причина отказа')),
                ('to_address', models.TextField(null=True, verbose_name='На адрес')),
                ('txid', models.TextField(null=True, verbose_name='Txid')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'db_table': 'transactions',
            },
        ),
        migrations.RemoveField(
            model_name='codes',
            name='btc_balance',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='rub_balance',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='curs_formula',
        ),
        migrations.AddField(
            model_name='codes',
            name='btc_balance_activator',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC стал у активировшего код'),
        ),
        migrations.AddField(
            model_name='codes',
            name='btc_balance_creator',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC стал у создателя кода'),
        ),
        migrations.AddField(
            model_name='codes',
            name='btc_balance_was_activator',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC был у активировшего код'),
        ),
        migrations.AddField(
            model_name='codes',
            name='btc_balance_was_creator',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC был у создателя кода'),
        ),
        migrations.AddField(
            model_name='codes',
            name='rub_balance_activator',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB стал у активировшего код'),
        ),
        migrations.AddField(
            model_name='codes',
            name='rub_balance_creator',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB стал у создателя кода'),
        ),
        migrations.AddField(
            model_name='codes',
            name='rub_balance_was_activator',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB был у активировшего код'),
        ),
        migrations.AddField(
            model_name='codes',
            name='rub_balance_was_creator',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB был у создателя кода'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='answer',
            field=models.TextField(null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='balance_btc',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC стал'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='balance_btc_was',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC был'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='balance_rub',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB стал'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='balance_rub_was',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB был'),
        ),
        migrations.AddField(
            model_name='replenish',
            name='btc_balance_was',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC был'),
        ),
        migrations.AddField(
            model_name='replenish',
            name='rub_balance_was',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB был'),
        ),
        migrations.AddField(
            model_name='wallets',
            name='currency',
            field=models.TextField(null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='btc_balance_was',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC был'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='rub_balance_was',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB был'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='dt',
            field=models.DateTimeField(null=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.TextField(null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='btc_value',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.TextField(null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='create_dt',
            field=models.DateTimeField(null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='currency',
            field=models.TextField(null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Время активации'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='rub_value',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='RUB'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='used_by_id',
            field=models.IntegerField(null=True, verbose_name='ID активировшего'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='admin_id',
            field=models.IntegerField(null=True, verbose_name='ID администратора'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='btc_value',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='commission',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='create_dt',
            field=models.DateTimeField(null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='currency_btc',
            field=models.FloatField(null=True, verbose_name='Курс BTC'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='currency_usd',
            field=models.FloatField(null=True, verbose_name='Курс USD'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='rub_value',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='RUB'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='type',
            field=models.IntegerField(null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='answer',
            field=models.TextField(null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='btc_balance',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='btc_value',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='city',
            field=models.IntegerField(null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='commission',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='country',
            field=models.IntegerField(null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='create_dt',
            field=models.DateTimeField(null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='currency',
            field=models.CharField(max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='rub_balance',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='rub_value',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='RUB'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='txid',
            field=models.TextField(null=True, verbose_name='txid'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='wallet_from',
            field=models.TextField(null=True, verbose_name='С кошелька'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='wallet_to',
            field=models.TextField(null=True, verbose_name='На кошелек'),
        ),
        migrations.AlterField(
            model_name='support',
            name='admin_id',
            field=models.IntegerField(null=True, verbose_name='ID администратора'),
        ),
        migrations.AlterField(
            model_name='support',
            name='connect_id',
            field=models.IntegerField(null=True, verbose_name='connect_id'),
        ),
        migrations.AlterField(
            model_name='support',
            name='from_who',
            field=models.TextField(null=True, verbose_name='Кто написал'),
        ),
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='support',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='support',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Время сообщения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='block',
            field=models.TextField(blank=True, null=True, verbose_name='Блокировка'),
        ),
        migrations.AlterField(
            model_name='users',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='btc_value',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='fio',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='users',
            name='history_email',
            field=models.TextField(blank=True, null=True, verbose_name='История email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='history_telephone',
            field=models.TextField(blank=True, null=True, verbose_name='История телефона'),
        ),
        migrations.AlterField(
            model_name='users',
            name='invited_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кем приглашен'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rub_value',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='users',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='wallet',
            field=models.TextField(null=True, verbose_name='Кошелек'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='answer',
            field=models.TextField(null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='btc_balance',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Баланс BTC'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='btc_payment',
            field=models.TextField(null=True, verbose_name='Кошелек BTC'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='btc_value',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='commission',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_dt',
            field=models.DateTimeField(null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='currency',
            field=models.TextField(null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='rub_balance',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Баланс RUB'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='rub_payment',
            field=models.TextField(null=True, verbose_name='Реквизиты RUB'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='rub_value',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='RUB'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='t_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='txid',
            field=models.IntegerField(null=True, verbose_name='txid'),
        ),
    ]
