# Generated by Django 3.2.5 on 2021-08-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0002_auto_20210827_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallets',
        ),
    ]
