# Generated by Django 3.2.5 on 2021-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0004_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='ID пользователя')),
                ('create_dt', models.DateTimeField(verbose_name='Время создания')),
                ('status', models.TextField(verbose_name='Статус')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('end_dt', models.DateTimeField(verbose_name='Время подтверждения')),
            ],
            options={
                'verbose_name': 'код email',
                'verbose_name_plural': 'коды email',
                'db_table': 'email_codes',
            },
        ),
    ]
