# Generated by Django 3.2.5 on 2021-08-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0005_email_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_codes',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Время подтверждения'),
        ),
    ]
