# Generated by Django 3.2.5 on 2021-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0006_alter_email_codes_end_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_codes',
            name='email',
            field=models.TextField(default='1', verbose_name='email'),
            preserve_default=False,
        ),
    ]
