# Generated by Django 3.2.5 on 2021-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0007_email_codes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenish',
            name='city',
            field=models.TextField(null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='country',
            field=models.TextField(null=True, verbose_name='Страна'),
        ),
    ]
