# Generated by Django 3.2.5 on 2021-08-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0008_auto_20210828_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='bank',
            field=models.TextField(null=True, verbose_name='Банк'),
        ),
    ]
