# Generated by Django 3.2.9 on 2021-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0012_exchange_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='min_btc',
            field=models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='Мин. сумма обмена в ₿'),
        ),
        migrations.AddField(
            model_name='commission',
            name='min_rub',
            field=models.DecimalField(decimal_places=2, max_digits=24, null=True, verbose_name='Мин. сумма обмена в ₽'),
        ),
    ]
