from enum import Enum
import redis


# token = '1799106051:AAHER6itgZ_472VgPHLf4PKmtYCBLa5vF2g'
token = '5094850730:AAFK7VBqxBdsm1QAqgZt9ooSDjIwRko7m3w'
# token_admin = '1758655220:AAH9lVFBkTdf-qQ038hz40P_GBqPlIQrKwc'
token_admin = '5053612158:AAEN6F1RYrY6vJvLrCX3aNIxd_XMREj01sA'
# token_support = '1860401579:AAGI74UjIgOkA-ZGNKIovlKAPCL7B63dgsg'
token_support = '5053612158:AAEN6F1RYrY6vJvLrCX3aNIxd_XMREj01sA'

host_ip = '127.0.0.1'
host_port = 8000  # 443, 80, 88, 8443
host_port_admin = 8000

# admin_host_port = 8443

ssl_cert = 'webhook_cert.pem'
ssl_priv = 'webhook_pkey.pem'

db_user = 'postgres'
db_pass = 'postgres'
db_host = '127.0.0.1'  # '91.122.48.176:3306'
db_name = 'changer'

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)


class State(Enum):
    ZERO = '0'
    MAIN_MENU = '1'
    
    OLD_BTC_TO_RUB_CALCULATOR = '2'
    OLD_RUB_TO_BTC_CALCULATOR = '3'
    OLD_CALCULATOR = '4'
    SET_EMAIL = '5'
    SET_PHONE_NUMBER = '6'
    SET_FIO = '7'
    CHANGE_EMAIL = '8'
    CHANGE_PHONE_NUMBER = '9'
    CHANGE_FIO = '10'
    ENTER_YANDEX_MONEY_TEMPLATE_NAME = '11'
    ENTER_YANDEX_MONEY_TEMPLATE_NUMBER = '12'
    ENTER_QIWI_TEMPLATE_NAME = '13'
    ENTER_QIWI_TEMPLATE_NUMBER = '14'
    ENTER_BANK_CARD_TEMPLATE_NAME = '15'
    ENTER_BANK_CARD_TEMPLATE_NUMBER = '16'
    ENTER_PAYEER_TEMPLATE_NAME = '17'
    ENTER_PAYEER_TEMPLATE_NUMBER = '18'
    ENTER_BTC_TEMPLATE_NAME = '19'
    ENTER_BTC_TEMPLATE_NUMBER = '20'
    EXCHANGE = '21'
    BTC_IN_VALUE = '22'
    RUR_IN_VALUE = '23'
    RUR_IN_SELECT_BANK = '24'
    BTC_OUT_VALUE = '25'
    RUR_OUT_SELECT_BANK = '26'
    RUR_OUT_VALUE = '27'
    BTC_TO_RUB_VALUE = '28'
    BTC_TO_RUB_RATE = '29'
    RUB_TO_BTC_VALUE = '30'
    RUB_TO_BTC_RATE = '31'
    BTC_TO_RUB_SELECT_BANK = '32'
    OLD_RUB_TO_BTC_SELECT_BANK = '33'

    LK = '34'
    SETTINGS = '35'
    REPLENISH_BTC_VALUE = '36'
    REPLENISH_RUB_VALUE = '37'
    START = '38'
    EMAIL_VERIFICATION_CODE = '39'
    ENTER_EMAIL = '40'
    WAIT_EMAIL_VERIFICATION_CODE = '41'
    WAIT_REPLENISH_CODE = '42'
    WAIT_CITY = '43'
    EXCHANGE_BTC_RUB_BUY_ENTER_AMOUNT = '44'
    EXCHANGE_BTC_RUB_SELL_ENTER_AMOUNT = '45'
    WAITING_WITHDRAW_BTC_SUM = '46'
    WAITING_WITHDRAW_RUB_SUM = '47'
    WAITING_WITHDRAW_RUB_CASH_CITY = '48'
    WAITING_WITHDRAW_RUB_CASH_SUM = '49'
    WAIT_COUNTRY = '50'
    ENTER_CODE_SUM = '51'
    WAITING_WITHDRAW_DECLINE_REASON = '52'
    WAITING_EXCHANGE_DECLINE_REASON = '53'
    WITHDRAW_BTC_WAIT_PAYMENT = '54'
    WITHDRAW_RUB_WAIT_PAYMENT = '55'

    CHANGE_COMMISSION_REPLENISH = '56'
    CHANGE_COMMISSION_EXCHANGE = '57'
    CHANGE_COMMISSION_WITHDRAW = '58'

    CHAT_WITH_SUPPORT = '59'
    ADMIN_ANSWER_TO_SUPPORT_QUESTION = '60'

    VERIFICATION_STEP1_FIO = '61'
    VERIFICATION_STEP1_DATE_OF_BIRTH = '62'
    VERIFICATION_STEP1_ADDRESS = '63'
    VERIFICATION_STEP2 = '64'
    VERIFICATION_STEP3 = '65'

    ADMIN_CHECK_VERIFICATION = '66'

    REPLENISH_BTC_WALLET = '67'

    WAITING_REPLENISH_DECLINE_REASON = '68'
    REPLENISH_TXID_ENTER = '69'
    WITHDRAW_TXID_ENTER = '70'
